### ISSUE TITLE
Remove empty lines in replacement

### ISSUE THREAD

**Issue by skywinder** [kohtenko/KOConstraintClean#3]
I don't know is nokogiri support such things, but it will be nice, to completley delete constarints, not to change it to empty lines.

![screen_shot_2015-07-21_at_09_33_10](https://cloud.githubusercontent.com/assets/3356474/8794387/fae79658-2f8b-11e5-875e-466c0d408987.jpg)

**Comment by kohtenko** [comment]
I agree, I don't like this ether. Will try to solve this in next build

**Comment by kohtenko** [comment]
https://github.com/kohtenko/KOConstraintClean/commit/3cb9d8b66518e7964adb9e33fac1a448ee4a380c fixes this

**Comment by skywinder** [comment]
:+1:
